In [ ]:
import pandas as pd

In [ ]:
ab=pd.read_csv("/content/loan_approval_dataset.csv")

In [ ]:
ab.head()

   Income  CreditScore  LoanApproved
0   40795          641             0
1   25860          698             0
2   63158          606             0
3   79343          743             1
4   69732          689             0

In [ ]:
ab.tail()

     Income  CreditScore  LoanApproved
295   33120          694             0
296   64384          645             0
297   72025          729             1
298   72254          634             0
299   46918          680             0

In [ ]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Income        300 non-null    int64
 1   CreditScore   300 non-null    int64
 2   LoanApproved  300 non-null    int64
dtypes: int64(3)
memory usage: 7.2 KB

In [ ]:
x=ab[["Income","CreditScore"]]
y=ab["LoanApproved"]

In [ ]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0])

In [ ]:
ab.tail()

     Income  CreditScore  LoanApproved
295   33120          694             0
296   64384          645             0
297   72025          729             1
298   72254          634             0
299   46918          680             0

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.8333333333333334

In [ ]:
 model.predict([[60000,850]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
confusion_matrix(y_test,y_pred)

array([[51,  6],
       [ 9, 24]])

In [ ]:
model.predict_proba([[60000,800]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[0.00469468, 0.99530532]])