In [ ]:
import pandas as pd

In [ ]:
RS=pd.read_csv("/content/retail_store_sales_dataset.csv")

In [ ]:
RS.head()

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20

In [ ]:
RS.tail()

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
215,5216,Hyderabad,Smart Bazaar,Home Decor,Jeans,1809,3,New,Card,15,5427,814.05,4612.95
216,5217,Mysore,Urban Retail,Beauty,Rice Bag,4696,1,Returning,Cash,15,4696,704.40,3991.60
217,5218,Pune,Smart Bazaar,Electronics,Jeans,3699,4,New,Cash,0,14796,0.00,14796.00
218,5219,Chennai,Urban Retail,Groceries,T-shirt,2845,4,New,UPI,15,11380,1707.00,9673.00
219,5220,Chennai,Central Mall,Home Decor,Headphones,2783,1,Returning,Card,10,2783,278.30,2504.70

In [ ]:
RS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    220 non-null    int64
 1   city              220 non-null    object
 2   store             220 non-null    object
 3   product_category  220 non-null    object
 4   product_name      220 non-null    object
 5   unit_price        220 non-null    int64
 6   quantity          220 non-null    int64
 7   customer_type     220 non-null    object
 8   payment_method    220 non-null    object
 9   discount_percent  220 non-null    int64
 10  total_sale        220 non-null    int64
 11  discount_amount   220 non-null    float64
 12  final_amount      220 non-null    float64
dtypes: float64(2), int64(5), object(6)
memory usage: 22.5+ KB

In [ ]:
RS.shape
#How many transactions are recorded in the dataset

(220, 13)

In [ ]:
RS["city"].unique()
#What are the different cities present in the dataset

array(['Pune', 'Bangalore', 'Hyderabad', 'Mysore', 'Chennai'],
      dtype=object)

In [ ]:
RS["product_category"].unique()
#How many product categories exist

array(['Home Decor', 'Clothing', 'Beauty', 'Electronics', 'Groceries'],
      dtype=object)

In [ ]:
len(RS["product_category"].unique())
#How many product categories exist

5

In [ ]:
RS.head(10)
#Display the first 10 rows

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20
5,5006,Mysore,Urban Retail,Electronics,Rice Bag,1652,4,Returning,UPI,0,6608,0.00,6608.00
6,5007,Hyderabad,Metro Mart,Home Decor,Wall Lamp,2739,2,New,Card,15,5478,821.70,4656.30
7,5008,Chennai,Central Mall,Electronics,Mixer,3899,3,New,Cash,15,11697,1754.55,9942.45
8,5009,Pune,Central Mall,Electronics,Wall Lamp,4628,3,Returning,UPI,10,13884,1388.40,12495.60
9,5010,Bangalore,City Center,Home Decor,Wall Lamp,2414,4,Returning,Card,5,9656,482.80,9173.20

In [ ]:
RS.groupby("product_category")["quantity"].sum().idxmax()
#Which product category is sold the most

'Groceries'

In [ ]:
RS.groupby("store")["total_sale"].sum().idxmax()
#Which store has the highest number of transaction

'Smart Bazaar'

In [ ]:
RS["city"].value_counts().idxmax()
#Which city has the most customers

'Hyderabad'

In [ ]:
RS["final_amount"].mean()
#What is the average purchase value

np.float64(5581.942045454545)

In [ ]:
RS["total_sale"].max()
#What is the maximum purchase value

19900

In [ ]:
RS.groupby("city")["final_amount"].sum().idxmax()
#Which city generates the highest revenue

'Hyderabad'

In [ ]:
RS["payment_method"].value_counts().idxmax()
# Which payment method is used the most

'Card'

In [ ]:
RS.groupby("customer_type")["final_amount"].sum().idxmax()
#Are new customers or returning customers purchasing more

'New'

In [ ]:
RS.groupby("product_category")["final_amount"].sum().idxmax()
# Which product category generates the highest revenue

'Groceries'

In [ ]:
RS.groupby("store")["discount_amount"].sum().idxmax()
#Which store gives the highest total discoun

'Smart Bazaar'

In [ ]:
RS.groupby("product_name")["quantity"].sum().idxmax()
#Which product sells the most units

'Mixer'

In [ ]:
RS.groupby("city")["final_amount"].mean().idxmax()
#Which city has the highest average purchase value

'Mysore'

In [ ]:
cu_Returning=RS[RS["customer_type"]=="Returning"]
cu_Returning['customer_type']
#Which product category is most popular among returning customers

0      Returning
2      Returning
3      Returning
5      Returning
8      Returning
         ...
211    Returning
212    Returning
213    Returning
216    Returning
219    Returning
Name: customer_type, Length: 114, dtype: object

In [ ]:
cu_Returning.groupby("product_category")["customer_type"].sum().idxmax()
#Which product category is most popular among returning customers

'Groceries'

In [ ]:
cu_Returning["product_category"].value_counts().idxmax()
#Which product category is most popular among returning customers

'Groceries'